config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  devise_for :admins
  root :to => 'visitors#index'
  resources :blogs
  post 'contactus', to: 'static#create'
  post 'enterprise', to: 'static#enterprisecreate'
  post 'business', to: 'static#businesscreate'
  post 'careers', to: 'static#careercreate'
  post 'carton', to: 'static#cartoncreate'
  resources :static
  get 'carton', :to => 'static#carton'
  get 'company', :to => 'static#company'
  get 'team', :to => 'static#team'
  get 'contactus', :to => 'static#contactus'
  get 'enterprise', :to => 'static#enterprise'
  get 'business', :to => 'static#business'
  get 'careers', :to => 'static#careers'
  get 'data-analytics', :to => 'static#analytics'
  get 'home', :to => 'visitors#index'
    authenticate :admin do
   devise_scope :admin do
       get 'admin-dashboard', to: 'admins/registrations#home', :as => :admin_root
   end
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:jobtitle, :jobrole, :jobresponsibility)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :jobtitle %>
    <%= form.text_field :jobtitle, id: :job_jobtitle %>
  </div>

  <div class="field">
    <%= form.label :jobrole %>
    <%= form.text_field :jobrole, id: :job_jobrole %>
  </div>

  <div class="field">
    <%= form.label :jobresponsibility %>
    <%= form.text_area :jobresponsibility, id: :job_jobresponsibility %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Jobtitle</th>
      <th>Jobrole</th>
      <th>Jobresponsibility</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.jobtitle %></td>
        <td><%= job.jobrole %></td>
        <td><%= job.jobresponsibility %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Jobtitle:</strong>
  <%= @job.jobtitle %>
</p>

<p>
  <strong>Jobrole:</strong>
  <%= @job.jobrole %>
</p>

<p>
  <strong>Jobresponsibility:</strong>
  <%= @job.jobresponsibility %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>