config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  devise_for :admins
  root :to => 'visitors#index'
  resources :blogs
  post 'contactus', to: 'static#create'
  post 'enterprise', to: 'static#enterprisecreate'
  post 'business', to: 'static#businesscreate'
  post 'careers', to: 'static#careercreate'
  post 'carton', to: 'static#cartoncreate'
  resources :static
  get 'carton', :to => 'static#carton'
  get 'company', :to => 'static#company'
  get 'team', :to => 'static#team'
  get 'contactus', :to => 'static#contactus'
  get 'enterprise', :to => 'static#enterprise'
  get 'business', :to => 'static#business'
  get 'careers', :to => 'static#careers'
  get 'data-analytics', :to => 'static#analytics'
  get 'home', :to => 'visitors#index'
    authenticate :admin do
   devise_scope :admin do
       get 'admin-dashboard', to: 'admins/registrations#home', :as => :admin_root
   end
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin_navigation.html.erb
<nav class="navbar navbar-default adminNavbar">
  <div class="container">
<%# if navbar collapse this part(image+button) will appear %>
         <div class="navbar-header">
               <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                     <span class="sr-only">Toggle navigation</span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
               </button>

               <%=  link_to 'ADMIN',"#", :class => 'navbar-brand hidden-lg' %>
         </div>
         <div class="collapse navbar-collapse" id="myNavbar">
               <ul class="nav navbar-nav adminNavbarLeft">
      	             <%= render 'layouts/admin_navigationlinks' %>
               </ul>
               <ul class="nav navbar-nav navbar-right adminNavbarRight">
               <li><%= image_tag "employees/raja.png", :class => 'img-circle img-responsive' %>
                   <ul class="dropdown-menu">
                         <li><%= link_to "Logout", destroy_admin_session_path, method: :delete %></li>
                  </ul>
                      
               </ul>
               </li>
         </div>
   </div> 
</nav>

app/views/layouts/_admin_navigationlinks.html.erb
   <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Blogs <span class="caret"></span></a>
     <ul class="dropdown-menu" role="menu">
      <li><a href="#"></a></li>
      <li><%= link_to 'Create Blog', new_blog_path %></li>
      <li><a href="#">View Blog</a></li>
     </ul>
   </li>
   <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Jobs <span class="caret"></span></a>
     <ul class="dropdown-menu" role="menu">
      <li><a href="#">View Jobs</a></li>
      <li><a href="#">Create Jobs</a></li>
     </ul>
   </li>
   

app/views/layouts/_cartonnavigation.html.erb
<%# carton navbar %>

<nav class="navbar navbar-default">
     <div class="container">
<%# if navbar collapse this part(image+button) will appear %>
         <div class="navbar-header">
               <button type="button" class="navbar-toggle navButton" data-toggle="collapse" data-target="#myNavbar">
                     <span class="sr-only">Toggle navigation</span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
               </button>
               
                <%=  image_tag "logo-makto.png", :class => 'logoHeader' %>
         </div>
         <div class="collapse navbar-collapse" id="myNavbar">
               <ul class="nav navbar-nav navbar-right cartonCustomNavbar-right">
      	             <%= render 'layouts/navigation_links' %>
               </ul>
         </div>
     </div>
</nav>

app/views/layouts/_cartonpage.html.erb
<!-- carton navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle cartonNavbarButton">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
         </button>
       <%= image_tag "carton-logo-section2.png", :class => 'logoHeader cartonLogo' %>
    </div>
   <div id="navbarCollapse" class="collapse navbar-collapse">
    <ul class="nav navbar-nav navbar-right cartonCustomNavbar-right">
        <%= render 'layouts/navigation_links' %>
    </ul>
   </div>
  </div>
</nav>
<!-- image first row -->
 <div class="row">
     <%= image_tag "carton-page/fullpage-img-warehouse.jpg", :class => 'img-responsive' %>
 </div>
<!-- second row  carton description-->
 <div class="row">
      <div id="display" class="col-lg-6 col-md-7 col-sm-7">
        <div class="manageInventory">
             <h1 class="cartonHeading">Manage inventory <br>without hassle free</h1>
             <p class="cartonContent">Carton is a real-time warehouse management<br class="hidden-xs">
               system that organize inventory, orders, shipments <br class="hidden-xs">
               and workflow for distributors, 3rd party logistics<br class="hidden-xs">
                companies and manufacturers.</p>
        </div>
      </div>
      <div class="col-lg-6 col-md-5 col-sm-5">
           <center>
               <%= image_tag "carton-page/cartong-warehouse-fulfilment.png", :class => 'img-responsive' %>
          </center>

      </div>
 </div>
 <!-- third row -->
 <div class="row cartonImageFirstRow"><!-- carton Image -->
   <div class="col-lg-6 col-md-6 col-sm-6 imageFullScreen">
      <%= image_tag "carton-page/img1.jpg", :class => 'img-responsive' %>
   </div>
   <div class="col-lg-6 col-md-6 col-sm-6 cartonFeatures">
        <h2>FEATURES</h2>
      <ul>
         <li>Integration to other ERP systems.</li>
         <li>Spans inbound orders and inventory.</li>
         <li>Reporting and communication on interactive dashboard.</li>
      </ul>
   </div>
 </div>
 <!-- carton Image Second Row -->
 <div class="row cartonImageSecondRow">
      <div class="col-lg-6 col-md-6 col-sm-6 cartonDeployment">
         <h2>DEPLOYMENT</h2>
        <ul>
          <li>On Premises.</li>
          <li>Setup on Cloud platforms Amazon Web Services(aws),<br class="hidden-xs hidden-sm hidden-md">Microsoft Azure, Google Cloud Platform</li>
          <li>Pay-as-you use</li>
        </ul>
          
      </div>
   <div class="col-lg-6 col-md-6 col-sm-6 imageFullScreen">
       <%= image_tag "carton-page/img2.jpg", :class => 'img-responsive' %>
   </div>
 </div>
 <div class="row">
      <center><button data-toggle="modal" data-target="#largeModal" class="btn cartonFormButton">WE WILL CALL YOU <span style="font-weight:100;display: block;">Drop your details</span></button></center>
 </div>
<!-- display notification -->
 <% if flash[:notice] %>
     <div class="row col-lg-offset-4">
       <h6 style="color:green;"> <%= flash[:notice] %></h6>
     </div>
 <% end %>

 <%= render 'layouts/footer' %>

<!-- navbar-fixed-top is initially transparent when scroll 750 the background color is #f8f8f8 -->
<script>
    $(document).ready(function(){
      $(window).scroll(function() { // check if scroll event happened
        if ($(document).scrollTop() > 750) { // check if user scrolled more than 50 from top of the browser window
          $(".navbar-fixed-top").css("background-color", "#f8f8f8"); // if yes, then change the color of class "navbar-fixed-top" to white (#f8f8f8)
         } else {
          $(".navbar-fixed-top").css("background-color", "transparent"); // if not, change it back to transparent
        }
      });
    });
</script>
<!-- Bootstrap Modal for Enterprise Form -->

<div class="modal fade" id="largeModal" tabindex="-1" role="dialog" aria-labelledby="largeModal" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <div class="pull-right">
           <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          </div>
        <h4 class="modal-title text-center" id="myModalLabel">ENQUIRY FOR CARTON</h4>
      </div>
      <div class="modal-body">
          <%= render 'static/carton_form' %>
      </div>
      <div class="modal-footer">
        <div class="pull-right">
            <button type="button" class="btn btn-danger btn-lg" data-dismiss="modal">Close</button>
        </div>
        
      </div>
      
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
 <div class="container-fluid">
<!-- footer first row -->
<div class="row firstFooter">
  <div class="col-lg-6 col-md-7 col-sm-8 col-xs-12 contactDetails">
        <div class="col-lg-5  col-xs-12 col-md-6 col-sm-6">
          <p><%= image_tag "footer/telephone.png" %>
            <span class="contactContent">CALL: 91-73391-88891</span></p>
        </div>
        <div class="col-lg-7  col-md-6 col-sm-6 col-xs-12 emailRow">
          <p><%= image_tag "footer/email.png" %>
            <span class="contactContent"> EMail: <%= link_to 'info@maktoinc.com', "http://www.google.com", target: "_blank"%></span></p>
        </div>
  </div>
  <div class="col-lg-6 col-md-5 col-sm-4 col-xs-12">
        <div class="col-lg-6 hidden-sm hidden-md hidden-xs">
        </div>
        <div class="socialMedia">
           Connect us
           <%= link_to image_tag("facebook.jpg", alt: "Facebook"), " http://www.facebook.com/maktoinc", target: :_blank, :class => 'socialMediaHeading'%>
           <%= link_to image_tag("twitter.jpg", alt: "twitter"), " http://www.twitter.com/maktoinc", target: :_blank %>
           <%= link_to image_tag("linkedin.png", alt: "linkedin"), "https://in.linkedin.com/company/makto-technology-private-limited", target: :_blank %>
        </div>
  </div>
</div>
<!-- footer second row -->
<div class="row secondFooter">
  <div class="col-lg-2 col-md-0">
   </div>
   <div class="col-lg-3 col-md-3 col-sm-4"><%# Products & solutions %>
     <h4>PRODUCTS & SOLUTIONS</h4>
      <div class="maktosubHeading">
   <!--  <%= link_to 'Toruk' %> -->  
         <%= link_to 'Carton', carton_path  %><br>
        <!--  <%= link_to 'Decksys', href="http://www.decksys.com", target: :_blank %> -->
      </div>
   </div>
   <div class="col-lg-3 col-md-2 col-sm-4"><%# Services %>
       <h4>SERVICES</h4>
      <div class="maktosubHeading">
    <!-- <%= link_to 'Cloud Management' %> -->
         <%= link_to 'Data Analytics', data_analytics_path %><br>
         <%= link_to 'Data Modeling',data_analytics_path(anchor: 'data-modeling') %><br>
         <%= link_to 'Data Visualisation', data_analytics_path(anchor: 'data-visualization') %><br>
        <!-- <div class="hidden-lg hidden-md"> -->
          <%= link_to 'Enterprise Mobility', enterprise_path %><br>
          <%= link_to 'Business Process Management', business_path %>
        <!-- </div> -->
      </div>
   </div>
   <!-- <div class="col-lg-2 col-md-3 hidden-sm hidden-xs"><%# Services  %>
       <div class="sequence">
         <%= link_to 'Enterprise Mobility', enterprise_path %><br>
         <%= link_to 'Business Process Management', business_path %>
       </div>
   </div> -->
   <div class="col-lg-3 col-md-2 col-sm-4"><%# Company %>
         <h4>COMPANY</h4>
       <div class="maktosubHeading">
         <%= link_to 'Team', company_path(anchor: 'team') %><br>
         <%= link_to 'About Makto', company_path %><br>
         
        <%= link_to 'Corporate Blog', blogs_path %>
        <!-- <div class="hidden-lg hidden-md">
            <%= link_to 'Corporate Blog', blogs_path %>
         </div> -->
       </div>
   </div>
   <!-- <div class="col-lg-2 col-md-2 hidden-sm hidden-xs"><%# Company %>
       <div  class="sequence">
         <%= link_to 'Corporate Blog', blogs_path %><br>
       </div>
   </div> -->
   <div class="col-lg-1 col-md-0">
   </div>
</div>
<%# Terms & Conditon %>
<div class="row thirdFooter">
   <div class="col-lg-8 col-md-8 col-sm-12  clearfix">
         <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <p> 
              <%= link_to 'Privacy Policy', home_path, :class => 'maktofooterStyle' %>
              <%= link_to 'Terms & Conditions', home_path, :class => 'maktofooterStyle' %>
              <%= link_to 'Contact Us', contactus_path  %>
            </p>
         </div>
         <div id="sec_box" class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <%= link_to 'Makto Technology Private Limited. IN', home_path %>
         </div>
   </div>
</div>
</div>
</div>

<script>
function footerAlign() {
  $('.footer').css('display', 'block');
  $('.footer').css('height', 'auto');
  var footerHeight = $('.footer').outerHeight();
  $('body').css('padding-bottom', footerHeight);
  $('.footer').css('height', footerHeight);
}


$(document).ready(function(){
  footerAlign();
});

$( window ).resize(function() {
  footerAlign();
});
</script>

app/views/layouts/_navigation.html.erb
<%# navbar for MaktoPortal %>
<nav class="navbar navbar-default">
     <div class="container">
<%# if navbar collapse this part(image+button) will appear %>
         <div class="navbar-header">
               <button type="button" class="navbar-toggle navButton" data-toggle="collapse" data-target="#myNavbar">
                     <span class="sr-only">Toggle navigation</span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
               </button>

             
              <%= link_to image_tag("logo-makto.png", alt: "MaktoLogo", :class => 'logoHeader'), home_path %>
         </div>
         <div class="collapse navbar-collapse" id="myNavbar">
               <ul class="nav navbar-nav navbar-right">
      	             <%= render 'layouts/navigation_links' %>
               </ul>
         </div>
     </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'COMPANY', company_path %></li>
<li class="dropdown">
	<a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">SERVICES<i class="fa fa-angle-down" style="font-size:16px;margin-left: 3px;"></i>
    </a>
     <ul class="dropdown-menu">
        <li><%= link_to 'Data Visualisation', data_analytics_path(anchor: 'data-visualization')%></li>
        <li><%= link_to 'Data Modeling', data_analytics_path(anchor: 'data-modeling') %></li>
       <li><%= link_to 'Enterprise Mobility', enterprise_path %></li>
       <li><%= link_to 'Business Process Automation', business_path %></li>
    </ul>
</li>
<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">PRODUCTS<i class="fa fa-angle-down" style="font-size:16px;margin-left: 3px;"></i>
    </a>
     <ul class="dropdown-menu">
        <!-- <li><%= link_to 'Decksys', href="http://www.decksys.com", target: :_blank %></li> -->
        <li><%= link_to 'Carton', carton_path %></li>
    </ul>
</li>
<li><%= link_to 'BLOG', blogs_path %></li>
<li><%= link_to 'CAREERS', careers_path %></li>
<li><%= link_to 'CONTACT US', contactus_path %></li>

app/views/layouts/admin_layout.html.erb
<html>
  <head>
    <title>Admin Layout</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  </head>
    
  <body>
    <%= render 'layouts/admin_navigation' %>
     
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html>
  <head>
    <title>Makto Technology Private Limited - Software & IT Services Company, India</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Josefin+Sans" />
  </head>

  <body>
    <div class="preloader"><span class="preloader-gif"></span></div>
  <% if action_name == "carton" %>
               <div class="container-fluid">
                  <%= render 'layouts/cartonpage' %>
                </div>
  <% else %>
            <%= render partial: 'layouts/navigation' %>
       <div class="container-fluid">
        <%= yield %>
        <%= render 'layouts/footer' %>
     </div>
 <% end %>

  </body>
</html>